Fix send-slack-message-on-failure job.
I realized that recently, the chaos-pipeline channel
wasn't receiving any notification. When checking the job
I saw the following error:
Error: Missing input! The webhook type must be 'incoming-webhook'
or 'webhook-trigger'.

This commit solves the missing type.